export const STRINGS = {
  appTitle: 'ROUND TIMER',
  heading: 'Shape the session.',
  subheading: 'Build rounds for any routine and stay on pace with clean, sharp cues.',
  ready: 'READY',
  round: 'Round',
  next: 'Next:',
  break: 'Break',
  reset: 'Reset',
  continue: 'Continue',
  sessionSettings: 'Session settings',
  roundLength: 'Round length',
  breakLength: 'Break length',
  rounds: 'Rounds',
  save: 'Save',
  cancel: 'Cancel',
  minutes: 'm',
  seconds: 's',
  savePreset: 'Save Preset',
  presetNamePrompt: 'Give this preset a name:',
  presetNamePlaceholder: 'e.g. HIIT Workout',
  selectPreset: 'Load preset...',
};
